version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./temp_audio:/app/temp_audio
      - ./instance:/app/instance  # For SQLite database
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

volumes:
  temp_audio:
