# render.yaml
services:
  # Основной веб-сервис
  - type: web
    name: rozoom-web-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python create_db.py && gunicorn "run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: postgresql://ittoken_db_user:Xm98VVSZv7cMJkopkdWRkgvZzC7Aly42@dpg-d0visga4d50c73ekmu4g-a.frankfurt-postgres.render.com/ittoken_db
